### ISSUE TITLE
Resources

### ISSUE THREAD

**Issue by rubix-coder** [ashishpatel26/365-Days-Computer-Vision-Learning-Linkedin-Post#1]
Hello @ashishpatel26 ,
I wish to start with 365 days of CV,
where can I find the resources starting from day 1 ?
Thanks,
[Jesal P](https://www.linkedin.com/in/jesalpatelindia)

**Comment by ashishpatel26** [comment]
You can follow this sequence it's same day 1 to day 365 in sequence format.

**Comment by ashishpatel26** [comment]
> Hello @ashishpatel26 , I wish to start with 365 days of CV, where can I find the resources starting from day 1 ? Thanks, [Jesal P](https://www.linkedin.com/in/jesalpatelindia)

You can follow this sequence it's same day 1 to day 365 in sequence format.
